name: 'Kingly page'
type: 'Site'
description: Configures a Kingly page content type.
recipes:
#  - core/recipes/basic_html_format_editor
  - kingly_paragraph_text

install:
  - entity_reference_revisions
  - path
  - user
  - node
  - menu_ui
  - search_api_exclude
  - paragraphs
  - layout_paragraphs

config:
  strict: false
  actions:
    system.site:
      simpleConfigUpdate:
        page.front: '/home'

