name: 'Kingly page'
type: 'Site'
description: Configures a Kingly page content type.
recipes:
  - core/recipes/basic_html_format_editor

install:
  - paragraphs
  - layout_paragraphs

config:
  strict: false
